services:
  - type: web
    name: repfy-backend
    env: node
    plan: standard
    rootDir: apps/api
    buildCommand: npm run build
    startCommand: npm run start
    installCommand: npm install --legacy-peer-deps
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: repfy_db
          property: connectionString
    routes:
      - path: /api
        destination: /api

databases:
  - name: repfy_db
    databaseName: repfy
    plan: standard
